// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5vejMQNKZgqgWtrVNkPjM
// Component: Fe6cuqvOFPq5D
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light_landing_page.module.css" // plasmic-import: j5vejMQNKZgqgWtrVNkPjM/projectcss
import * as sty from "./PlasmicFeatureCard.module.css" // plasmic-import: Fe6cuqvOFPq5D/css

export const PlasmicFeatureCard__VariantProps = new Array("long")

export const PlasmicFeatureCard__ArgProps = new Array(
  "iconFront",
  "title",
  "description",
  "iconBack"
)

function PlasmicFeatureCard__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__long]: hasVariant(variants, "long", "long"),
      })}
    >
      {(hasVariant(variants, "long", "long") ? false : true) ? (
        <div
          className={classNames(defaultcss.all, sty.box___6MbK, {
            [sty.box__long___6MbKLk2Wm]: hasVariant(variants, "long", "long"),
          })}
        >
          <div
            className={classNames(defaultcss.all, sty.box__ceXkk, {
              [sty.box__long__ceXkkLk2Wm]: hasVariant(variants, "long", "long"),
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: (
                <svg
                  className={classNames(defaultcss.all, sty.svg__q2RLx)}
                  role={"img"}
                />
              ),

              value: args.iconFront,
            })}
          </div>
        </div>
      ) : null}

      <div
        className={classNames(defaultcss.all, sty.box__w2GTg, {
          [sty.box__long__w2GTgLk2Wm]: hasVariant(variants, "long", "long"),
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Title",
          value: args.title,
          className: classNames(sty.slotTitle, {
            [sty.slotTitle__long]: hasVariant(variants, "long", "long"),
          }),
        })}

        {p.renderPlasmicSlot({
          defaultContents:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          value: args.description,
          className: classNames(sty.slotDescription, {
            [sty.slotDescription__long]: hasVariant(variants, "long", "long"),
          }),
        })}
      </div>

      {(hasVariant(variants, "long", "long") ? true : false) ? (
        <div
          className={classNames(defaultcss.all, sty.box__jLw9, {
            [sty.box__long__jLw9Lk2Wm]: hasVariant(variants, "long", "long"),
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <svg
                className={classNames(defaultcss.all, sty.svg__k2Ety)}
                role={"img"}
              />
            ),

            value: args.iconBack,
          })}
        </div>
      ) : null}
    </p.Stack>
  )
}

const PlasmicDescendants = {
  root: ["root"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeatureCard__ArgProps,
      internalVariantPropNames: PlasmicFeatureCard__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicFeatureCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicFeatureCard"
  } else {
    func.displayName = `PlasmicFeatureCard.${nodeName}`
  }
  return func
}

export const PlasmicFeatureCard = Object.assign(
  // Top-level PlasmicFeatureCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFeatureCard
    internalVariantProps: PlasmicFeatureCard__VariantProps,
    internalArgProps: PlasmicFeatureCard__ArgProps,
  }
)

export default PlasmicFeatureCard
/* prettier-ignore-end */
